Improve `isfs` folder creation/modification UX
intersystems-community/vscode-objectscript pull request #1090
Opened 2023-02-13 12:58 UTC by isc-bsaviano

IMO our existing command for creating an `isfs` workspace folder have 2 weaknesses:

- It can't be re-used to modify an existing folder. 
- It doesn't allow you to add query parameters. The Studio equivalents can be easily accessed in a menu.

This PR changes the command to allow for the addition of query parameters and for the most of the code to be re-used in a new "modify existing `isfs` folder" command. I also updated the docs to show the new UI.

2023-02-16 19:38 UTC, gjsjohnmurray commented
Based only on reading the diffs I found the new step shown in docs/assets/images/ss-query-params.png hard to understand. Seems like I either set only the first checkbox, or only the second, or neither of those but zero or more of the others.

Did you rule out having a single-choice quickpick to handle ordinary, csp or project, followed by the multi-select one if the choice was o"ordinary"?

Did you consider making it a multi-step procedure, so I can back up to a previous step?

2023-02-16 19:43 UTC, isc-bsaviano commented
@gjsjohnmurray Looking at this with fresh eyes I see the confusion. I think splitting it up into 2 steps makes sense, but I'm not sure what the call the "ordinary" step that leads to the other query params, or what the prompt for that first step should be.

2023-02-16 20:02 UTC, isc-rsingh commented
Can't look at this until tomorrow AM

2023-02-16 21:45 UTC, isc-rsingh commented
Since project rules out other choices, that should be the first step (title="Open Project", options=yes/no). Then if project isn't selected, go to CSP (title="Show web application files", options=yes/no), then type or filter.

2023-02-16 21:50 UTC, isc-bsaviano commented
I prefer John's 2 step approach if I can get the labels right. I'll keep working on this and update the PR when I think of something.

2023-02-17 12:47 UTC, isc-bsaviano commented
@gjsjohnmurray @isc-rsingh I just pushed a new commit that split up the query parameter QuickPick and changed the language a little. Let me know what you think.

2023-02-17 21:00 UTC, isc-rsingh commented
Much improved

2023-02-17 21:00 UTC, isc-rsingh approved these changes

2023-02-23 14:27 UTC, isc-bsaviano commented
@gjsjohnmurray If you don't have any comments I'm going to merge this.

2023-02-23 14:39 UTC, gjsjohnmurray commented
@isc-bsaviano I'm busy prepping for a webinar we're giving later today. Should be able to look at PRs tomorrow.

2023-02-24 12:52 UTC, gjsjohnmurray requested changes
I have made some inline suggestions.

I also think this could be improved:

![image](https://user-images.githubusercontent.com/6726799/221182206-b51ed09c-4dd6-4c70-9287-8b8c39fb815e.png)

The short lowercase labels feel a bit cryptic. I would prefer:
- Filter
- Flat List
- Generated Code
- Mapped Code

Either your switch statement would need to be amended as well, or you could extend QuickPickItem to add, say, a `value` property to each option and use that in your switch.

I also find it confusing that on this dialog `generated` is about **showing** and `mapped` is about **hiding**. Under the covers both are about showing. How about pre-selecting mapped if it's a new definition or if the existing definition doesn't specify a value? Alternatively make the option labels be "Show Generated" and "Hide Mapped".

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +        label: "$(files) Show the contents of a server-side project.",
```suggestion
        label: "$(files) Contents of a Server-side Project",
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +        label: "$(list-tree) Show files that pass through custom filters.",
```suggestion
        label: `$(list-tree) Code Files in ${namespace}`,
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +        detail: "Choose an existing project or create a new one.",
```suggestion
        detail: "Choose an existing project, or create a new one.",
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +        title: "Pick a specific web application to show, or press 'Escape' to show all.",
```suggestion
        placeHolder: "Pick a specific web application to show, or press 'Escape' to show all",
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +        detail: "Choose the filters to apply.",
```suggestion
        detail: "Filters can be applied in the next step.",
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +      vscode.window.showInformationMessage("No web applications are configured in this namespace.", "Dismiss");
```suggestion
      vscode.window.showWarningMessage(`No web applications are configured to use namespace ${namespace}.`, "Dismiss");
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +        title: "",
```suggestion
        placeHolder: "Add optional filters",
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +          detail: "Show a flat list of files. Does not split packages as folders.",
```suggestion
          detail: "Show a flat list of files. Do not treat packages as folders.",
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +          detail: "Comma-delimited list of search options. (i.e. '*.cls,*.inc,*.mac,*.int')",
```suggestion
          detail: "Comma-delimited list of search options, e.g. '*.cls,*.inc,*.mac,*.int'",
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +          detail: "Hide files that are mapped from a non-default database.",
```suggestion
          detail: `Hide files that are mapped into ${namespace} from another code database.`,
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +          detail: "Show generated files as well as non-generated.",
```suggestion
          detail: "Also show files tagged as generated, e.g. by compilation.",
```

2023-02-24 12:52 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +        placeHolder: "Pick the workspace folder modify.",
```suggestion
        placeHolder: "Pick the workspace folder to modify",
```

2023-02-24 13:23 UTC, isc-bsaviano commented
@gjsjohnmurray  `mapped` is hide but `generated` is show because by default StudioOpenDialog shows `mapped` files but hides `generated` ones. I can either switch the names like you suggested, or I can select mapped by default and handle that item separately.

2023-02-24 13:51 UTC, gjsjohnmurray requested changes
A couple more tweaks.

Re 'mapped', I don't mind whether you opt to change the label or pre-select the checkbox.

Also, when testing the modify path I noticed that the "what to show" quickpick defaults to the first item even though the URI I'm modifying was created using the third item (i.e. it's a regular one for code in a namespace). I think you could pre-select the right item, but only if you use `createQuickPick` and friends rather than the convenience of `showQuickPick`.

While on the subject of that particular quickpick, how about changing the order so "Code Files in XXX" comes first?

2023-02-24 13:51 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +    { title: "Choose the type of access", ignoreFocusOut: true }
```suggestion
    { placeHolder: "Choose the type of access", ignoreFocusOut: true }
```
For consistency with the other steps.

2023-02-24 13:51 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +              "Patterns are comma-delimited and may contain both * (any number of characters) and ? (a single character) as wildcards. To exclude items, prefix the pattern with a single quote.",
```suggestion
              "Patterns are comma-delimited and may contain both * (zero or more characters) and ? (a single character) as wildcards. To exclude items, prefix the pattern with a single quote.",
```

2023-02-24 13:51 UTC, gjsjohnmurray commented on src/commands/addServerNamespaceToWorkspace.ts
> +    title: "Enter a name for the workspace folder.",
```suggestion
    title: "Enter a name for the workspace folder",
```

2023-02-24 14:08 UTC, gjsjohnmurray commented
I just discovered that if I'm trying to add a web-app-type folder from a server I haven't already connected to, I get told that there are no web apps on the server which use the namespace I chose. This happens because `cspAppsForUri` relies on information in the `cspApps` map which only gets put there by an `await checkConnection(false, uri)` which hasn't yet happened.

2023-02-24 14:10 UTC, isc-bsaviano commented
@gjsjohnmurray Good catch, I will change that to fetch the list from the server

2023-02-24 14:46 UTC, gjsjohnmurray commented
When I use the Modify feature on a uri that I had manually added `?system=1` this gets dropped.

Did you consider adding a filter option for including system items? Either way, existing queryparams that the dialog doesn't handle should be preserved IMO.

Also noticed that if I start a modify but don't change anything on the way through I get told "Failed to modify...".

And I suggest we be consistent about capitalization of `Server-Side` (in the Modify command vs `Server-side` (in the quickpick option about projects).

2023-02-24 14:58 UTC, isc-bsaviano commented
@gjsjohnmurray I didn't create an entry for `system` because it's undocumented. I can do that though. The only other param is `type`, which I do not want to create an entry for.

2023-02-24 15:38 UTC, gjsjohnmurray commented
Latest build no longer seems to update the URI when I use the Modify command. Here's my workspace definition:

```json
{
	"folders": [
		{
			"name": "iris231:USER",
			"uri": "isfs://iris231:user/?mapped=0&system=1"
		}
	],
	"settings": {
		"objectscript.showExplorer": false
	}
}
```

When I get to the checkboxes in the Modify pathway the last two are correctly checked. But if I uncheck either or both of these, OK the quickpick, OK the name (changed or unchanged) the uri in my workspace definition doesn't change.

2023-02-24 15:49 UTC, isc-bsaviano commented
@gjsjohnmurray Sorry about that, my last commit should fix it. I now clear out all known query parameters but leave intact ones that I don't know (like `type`).

2023-02-24 17:33 UTC, isc-bsaviano commented
Sorry, that got lost in the shuffle. I'll take a look

2023-02-24 17:57 UTC, isc-bsaviano commented
@gjsjohnmurray Done

2023-02-24 18:02 UTC, gjsjohnmurray approved these changes
LGTM

2023-02-24 18:09 UTC, merged

2023-02-24 19:25 UTC, gjsjohnmurray commented
Too late for this PR I know, but maybe this step would be clearer with an explicit "<all applications>" entry in the quickpick:

![image](https://user-images.githubusercontent.com/6726799/221272794-19ba5c4c-d7e7-4096-86c1-52045edf8f9f.png)

2023-02-24 19:29 UTC, isc-bsaviano commented
That's a good suggestion! Maybe an entry called `All`?