Add WebSocket Terminal support
intersystems-community/vscode-objectscript pull request #1150
Opened 2023-05-15 14:12 UTC by isc-bsaviano

This PR adds support for for the new terminal endpoint added in Atelier API v7. It will be available in the next preview of IRIS 2023.2. See the new documentation included in this PR for how to start the terminal and what features it supports.

2023-05-15 15:29 UTC, isc-rsingh approved these changes

2023-05-15 15:37 UTC, gjsjohnmurray commented on docs/RunDebug.md
> +4. Once the error appears, copy the contents of the `^IRIS.Temp.Atelier("terminal")` global and add it to your GitHub issue.
If this trace global might contain confidential data then we should probably advise people to mask that before posting.

2023-05-15 15:39 UTC, gjsjohnmurray commented
I look forward to trying this out as soon as a suitable 2023.2 preview becomes available.

2023-05-24 13:06 UTC, isc-bsaviano commented
This can be tested with the [2nd 2023.2 developer preview kit](https://community.intersystems.com/post/developer-preview-2-intersystems-iris-iris-health-20232) (2023.2.0.201.0)

2023-05-24 14:16 UTC, daimor commented
That's very interesting

2023-05-24 17:19 UTC, daimor commented
Well, 
The terminal thing itself looks good, looks working

But there are a few Issues

When connection is disable, it keeps showing in this add terminal menu
<img width="339" alt="image" src="https://github.com/intersystems-community/vscode-objectscript/assets/1212251/a210cd88-b65d-4097-8e33-ea07f36e4392">

But, in the list of main commands shown only when any ObjectScript file is open, even if the connection is active

And in the project with a Python virtual environment, made with venv, VSCode activates this virtual environment when opened a new terminal. No idea if it can be configured somehow, probably it's just implemented a way, that it sends this command to any terminal.
<img width="453" alt="image" src="https://github.com/intersystems-community/vscode-objectscript/assets/1212251/ac0125a8-1a56-4001-b0bc-835a0594cb42">

to reproduce it, 
create a new virtual environment in the project and switch to it, VSCode should notice a new environment and offer to switch to it
```
python -m venv venv
source venv/bin/activate
```

2023-05-24 17:21 UTC, daimor requested changes

2023-05-24 17:21 UTC, daimor commented on package.json
> +          "when": "editorLangId =~ /^objectscript/ && vscode-objectscript.connectActive"
```suggestion
          "when": "vscode-objectscript.connectActive"
```

2023-05-24 17:36 UTC, isc-bsaviano commented
@daimor The `terminal.profiles` contribution point doesn't take a `when` clause, so I can' hide it when there's no active connection. I could open a  VS Code issue but I doubt it would be resolved before this PR is merged. The second image looks like a bug in whatever code sends that command. It should check that the terminal isn't an extension terminal before sending it. I'm not sure where you should report that.

2023-05-24 17:39 UTC, daimor commented
well, ok then

2023-05-24 17:39 UTC, daimor submitted a review, later dismissed

2023-05-24 17:42 UTC, isc-bsaviano commented
FYI reported the when clause issue: https://github.com/microsoft/vscode/issues/183354

2023-05-24 18:03 UTC, gjsjohnmurray commented
For the venv issue see https://github.com/microsoft/vscode-python/issues/20562

2023-05-25 15:36 UTC, gjsjohnmurray requested changes
Some comments made. I haven't yet had time to install a 2023.2 that I can actually test the terminal with.

2023-05-25 15:36 UTC, gjsjohnmurray commented on src/commands/webSocketTerminal.ts
> +    vscode.window.showErrorMessage("WebSocket Terminal requires Atelier API version 7 or above.", "Dismiss");
I suggest stating the IRIS version rather than the API version, as the latter is meaningless to most.

2023-05-25 16:02 UTC, isc-bsaviano commented on src/commands/webSocketTerminal.ts
> +        await vscode.window.showWorkspaceFolderPick({
I think using the prebuilt QuickPick is fine

2023-05-25 16:21 UTC, gjsjohnmurray approved these changes

2023-05-25 16:22 UTC, merged