PR to fix my previous issues.
intersystems-community/vscode-objectscript pull request #1277
Opened 2023-12-06 04:40 UTC by hsyhhssyy

The current version of the plugin still has several unresolved issues that I have encountered, detailed as follows:

1. When openning server-side Classes using ObjectScript Explorer, pressing Ctrl+S and select a folder from the current workspace invariably prompts a question about overwriting. This happens because, upon file creation, the plugin automatically inserts a stub class code which often has a) an incorrect Package, and b) invariably triggers an overwrite prompt.
2. The issue of the Class file's Package being altered during movement persists in the latest version of the plugin. Every scenario I reported in my previous case still occurs.
3. When a file is a binary file but has a .cls extension, dragging it between folders in VSCode can corrupt its binary structure.
4. 
To thoroughly address these issues, I have submitted this PR. The PR introduces a new VSCode option designed to prevent any automated Code Formatter actions without explicit user permission. Any write operations to code files not executed through the user's ContextMenu will be disabled.

Currently, it only acts on onDidCreateFiles to prevent the automatic addition of PackageNames to code. If further similar behaviors are identified in the future, I plan to extend its control scope. For instance, if an ObjectScript Lint is introduced later, the option would block the automatic application of Lint when saving files with Ctrl+S. Users would need to explicitly apply Lint by right-clicking in the file and selecting FormatCurrentFile.

2023-12-06 04:42 UTC, hsyhhssyy commented
Related Issue: https://github.com/intersystems-community/vscode-objectscript/issues/1256

2023-12-06 13:25 UTC, isc-bsaviano requested changes
@hsyhhssyy Thank for the PR. I've added some suggestions above.

@gjsjohnmurray @isc-rsingh Can you take a look at this as well? I think the language of the new setting needs some work.

2023-12-18 04:55 UTC, hsyhhssyy commented
I've accepted these suggestions and committed new code.

2023-12-19 12:39 UTC, gjsjohnmurray submitted a review, later dismissed

2023-12-27 18:04 UTC, isc-rsingh submitted a review, later dismissed

2023-12-27 18:08 UTC, isc-bsaviano commented
@hsyhhssyy Thanks for making the suggested changes! I'm getting ready to merge this PR, but one of our CI tests is failing due to linting issues. Can you run `npm run lint-fix` in your branch and push the changes that get made?

2023-12-28 05:48 UTC, hsyhhssyy commented
I have executed `npm run lint-fix` and submitted a new commit.

2023-12-28 12:48 UTC, merged

2023-12-28 12:49 UTC, isc-bsaviano commented
Thanks @hsyhhssyy, I just merged your PR!