Improve language configuration
intersystems-community/vscode-objectscript pull request #1311
Opened 2024-02-08 19:56 UTC by isc-bsaviano

* Rolls back #1298
* Adds auto-closing of C-style block comments (e.g. typing `/*` automatically adds `*/`)
* Adds new `const`s for language ID's to improve code readability and maintainability

2024-02-08 21:46 UTC, isc-rsingh approved these changes

2024-02-09 09:04 UTC, gjsjohnmurray requested changes
Reviewed code and commented, but not yet tested.

2024-02-09 09:04 UTC, gjsjohnmurray commented on src/extension.ts
> +        documentSelector(clsLangId, macLangId, intLangId, cspLangId),
Why did `"objectscript-macros"` become `cspLangId` rather than `incLangId`?

2024-02-09 09:04 UTC, gjsjohnmurray commented on src/extension.ts
> +        documentSelector(clsLangId, macLangId, intLangId, cspLangId),
Why did `"objectscript-macros"` become `cspLangId` rather than `incLangId`?

2024-02-09 09:04 UTC, gjsjohnmurray commented on src/extension.ts
> +        documentSelector(clsLangId, macLangId, intLangId, cspLangId),
Why did `"objectscript-macros"` become `cspLangId` rather than `incLangId`?

2024-02-09 09:04 UTC, gjsjohnmurray commented on src/extension.ts
> +        documentSelector(clsLangId, macLangId, intLangId, cspLangId),
Why did `"objectscript-macros"` become `cspLangId` rather than `incLangId`?

2024-02-09 09:04 UTC, gjsjohnmurray commented on src/extension.ts
> +        documentSelector(clsLangId, macLangId, intLangId, cspLangId),
Why did `"objectscript-macros"` become `cspLangId` rather than `incLangId`?

2024-02-09 12:32 UTC, isc-bsaviano commented
@gjsjohnmurray Thanks for the through review. I've applied your suggestions.

2024-02-09 13:04 UTC, gjsjohnmurray commented on src/languageConfiguration.ts
> +      lineComment: ["objectscript-class", "objectscript-int"].includes(lang) ? "//" : "#;",
Fair enough

2024-02-09 13:17 UTC, merged