Fire source control hooks when creating/opening/editing/deleting projects
intersystems-community/vscode-objectscript pull request #1313
Opened 2024-02-13 21:42 UTC by isc-bsaviano

This PR fixes #1312

I think this is the best I can do with "other" actions to approximate what happens when a file is opened via the Atelier GET /doc/ API. @gjsjohnmurray I'd really appreciate your review on this since since you're a server-side source control expert.

2024-02-14 09:30 UTC, gjsjohnmurray requested changes
Looks good as code, with only one minor comment made. I haven't tested it but I think the person who raised the issue is better placed to do that.

2024-02-14 09:30 UTC, gjsjohnmurray commented on src/commands/project.ts
> +        await new StudioActions().fireProjectUserAction(api, name, OtherStudioAction.CreatedNewDocument);
Do we need two new StudioActions objects here or can we create one into a const and use it twice?

2024-02-14 12:31 UTC, isc-bsaviano commented
Thanks for the review @gjsjohnmurray! I've added your suggestion as well as a few more changes.

2024-02-14 17:31 UTC, gjsjohnmurray submitted a review, later dismissed
LGTM but not tested

2024-02-15 16:10 UTC, isc-rsingh approved these changes

2024-02-15 16:49 UTC, gjsjohnmurray approved these changes

2024-02-21 19:47 UTC, trevorfstrong commented
Hi @isc-bsaviano we have always wanted the exposure of the current project opened for the current document to be passed to VSC studio Source Control hooks. Sounds like this might do the trick.
How can we update the plugin to trial this with our studio hooks?

2024-02-21 19:54 UTC, isc-bsaviano commented
@trevorfstrong I just re-read your request and I think it may be unrelated to this PR. This PR fires OtherStudioActions for .PRJ files. Is that what you're asking for, or do you mean something else?

2024-02-21 20:13 UTC, isc-bsaviano commented
@trevorfstrong Something like that is going to be very difficult to implement in VS Code. VS Code doesn't really "open" projects, it just treats them as a SQL table that defines a group of documents. Since users can have multiple projects "open" at once (via the multi-root workspace feature) and REST connections can go through a number of CSP jobs, there isn't a good way to persist that information on the server.

2024-02-21 20:32 UTC, trevorfstrong commented
ok, but if you passed the project in this screenshot when you "access" a document that is linked to the project, we can persist it on the back end as the last project "touched" by vsc.
![image](https://github.com/intersystems-community/vscode-objectscript/assets/159860830/444e0128-419c-4b17-8dbf-1efeb3f205b3)

2024-02-21 20:57 UTC, isc-bsaviano commented
I understand. It would be possible to pass the project with the REST requests somehow and "open" it for the duration that the request is processed so any source control hooks see it. That would require a bunch of IRIS-side changes though. I would need to discuss that internally before drawing up a spec or committing to doing that work.

2024-02-21 21:13 UTC, trevorfstrong commented
Thanks for your attention on this subject Brett.

2024-02-22 12:29 UTC, isc-bsaviano commented
Thanks for bringing this to my attention! I will add this to my notes for when we have a larger discussion about projects support in VS Code.

2024-02-22 12:30 UTC, merged

2024-02-24 01:15 UTC, trevorfstrong commented
Hi Brett.
Looks like the firing of project actions in the latest code is always triggered before items for source control actions, so i believe i can work with that. No need for any further mods

2024-02-28 07:11 UTC, trevorfstrong commented
Hi again.
When we have multiple projects associated with the workspace and we select a file that is in a specific project, you fire the src ctrl actions for all projects in the workspace then that selected file, but the projects are simply looped thru in the order they are presented in the workspace when fired, so is there any way the project src ctrl action that the current file selected is in be fired last? e.g. before the currently selected file?

2024-02-28 07:13 UTC, trevorfstrong commented
![image](https://github.com/intersystems-community/vscode-objectscript/assets/159860830/51de84ef-e797-4e21-9c80-f3ac94d7f0b7)