Docs logo
intersystems-community/vscode-objectscript pull request #308
Opened 2020-08-30 04:23 UTC by rajrsingh

This PR fixes #

2020-08-30 05:52 UTC, daimor approved these changes

2020-09-01 09:55 UTC, gjsjohnmurray requested changes
The circle seems to have been clipped top and bottom:

![image](https://user-images.githubusercontent.com/6726799/91835702-a4cab980-ec41-11ea-8d7d-4638c8571515.png)

Can this be fixed?

2020-09-03 02:32 UTC, rajrsingh commented
@gjsjohnmurray @daimor check it out again. You shouldn't see that clipping anymore.

2020-09-03 08:55 UTC, gjsjohnmurray approved these changes
LGTM

2020-09-03 08:56 UTC, merged