Solon snippets
intersystems-community/vscode-objectscript pull request #493
Opened 2020-11-09 20:30 UTC by isc-solon

This PR improves some snippets and adds some new ones. The details are in the two commits.

2020-11-10 01:23 UTC, gjsjohnmurray requested changes
Looking good.

In addition to my suggested change to the prefix of the Property snippet, please reinstate the 2-space indents of snippet properties in place of the tabs you seem to be using, e.g.
```
  "Method definition": {
	"prefix": "Method",
	"body": ["Method $1($2) As ${3:%Status}", "{", "\tset $4 = \\$\\$\\$OK", "\t$0", "\treturn $4", "}"]
  },
```
becomes
```
  "Method definition": {
    "prefix": "Method",
    "body": ["Method $1($2) As ${3:%Status}", "{", "\tset $4 = \\$\\$\\$OK", "\t$0", "\treturn $4", "}"]
  },
```

2020-11-10 01:23 UTC, gjsjohnmurray commented on snippets/objectscript-class.json
>      "prefix": "property",
```suggestion
    "prefix": "Property",
```

2020-11-10 17:44 UTC, isc-solon commented
I think I got everything

2020-11-10 17:53 UTC, gjsjohnmurray submitted a review, later dismissed
👍

2020-11-10 17:54 UTC, gjsjohnmurray commented
@daimor I'll leave it to you to review (or not) and then to do the merge.

2020-11-10 18:01 UTC, isc-solon commented
Once this is merged, I have another proposal for _objectscript-class.json_. I'd like to add `/// $1` to the top of **all** of the snippets so that all the class members include documentation. Which means that all the other $#s would have to be "incremented" by 1. Do you like that idea?

2020-11-11 23:57 UTC, isc-solon commented
Don't approve yet! I just thought of one more thing...

2020-11-12 00:12 UTC, gjsjohnmurray approved these changes
👍

2020-11-12 00:13 UTC, merged