Document new features for ServerManager 2.0
intersystems-community/vscode-objectscript pull request #653
Opened 2021-05-12 15:27 UTC by jstetson10

This PR fixes #

2021-05-12 17:07 UTC, isc-rsingh submitted a review, later dismissed

2021-05-13 08:57 UTC, gjsjohnmurray requested changes
Looking good. I have suggested some changes inline.

It would also be good to get the new `system=1` isfs parameter added to the 'Filters and Display Options' section of ServerSide.md. I suggest this line immediately after the existing one describing generated=1:

```
- `isfs://myserver:user?system=1`, shows %-files in non-%SYS namespaces
```

2021-05-13 08:57 UTC, gjsjohnmurray commented on docs/ExtensionUI.md
> +Entries from menus with any other name appear in the **Server Command Menu...**.
```suggestion
Entries from menus with any other name appear in the **Server Command Menu...**.

## Views and View Containers

Technically the 'InterSystems Tools' and 'Explorer' entities described above are what VS Code calls [view containers](https://code.visualstudio.com/api/extension-capabilities/extending-workbench#view-container). Each contains a single view:
- in container **InterSystems Tools** is view **Servers**
- in container **ObjectScript** is view **Explorer**

When a VS Code container has only a single view in it the view header merges with the container header, with the two names separated by a colon.

Views can be dragged between containers, so for example you could move Explorer off its ObjectScript container and onto the InterSystems Tools container. Or move Servers onto the ObjectScript container. Or move either of them onto VS Code's main Explorer container.
```

2021-05-13 08:57 UTC, gjsjohnmurray commented on docs/ServerSide.md
> +The string `isfs` which appears in the **uri** for folders configured for server-side editing is an abbreviation created by InterSystems which stands for **InterSystems File Service**. It implements
```suggestion
The string `isfs` which appears in the **uri** for folders configured for server-side editing is an abbreviation created by InterSystems which stands for **InterSystems File Service**. It implements the VS Code [FileSystemProvider API](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider), which lets you make any remote location look like a local one. It works well for making artifacts in an InterSystems IRIS namespace look like local files.
```

2021-05-17 18:27 UTC, isc-rsingh commented on docs/Configuration.md
>  ## Configuring a Server
This will be addressed in a future update

2021-05-17 18:33 UTC, isc-rsingh commented on docs/Configuration.md
> +To remove a password from the keychain, Select **View > Command Palette > InterSystems Server Manager: Clear Password from Keychain**. The commands to both store and clear passwords are also availabl
We will take a closer look at this suggestion.

2021-05-17 18:34 UTC, isc-rsingh approved these changes

2021-05-17 18:38 UTC, merged