Add support for conditional breakpoints
intersystems-community/vscode-objectscript pull request #764
Opened 2021-11-04 17:19 UTC by isc-bsaviano

This PR adds support for [conditional breakpoints.](https://code.visualstudio.com/docs/editor/debugging#_conditional-breakpoints) Note that due to a limitation in the Atelier debugger implementation, we can only support hit conditions that are integers instead of more complex expressions.

2021-11-04 19:00 UTC, gjsjohnmurray reviewed
I'm going to recuse myself from reviewing this because of a conflict of interests with our own debugger.

2021-11-04 19:23 UTC, isc-bsaviano commented
@gjsjohnmurray That's reasonable.

@daimor Can you please give this a look before our meeting tomorrow?

2021-11-04 20:17 UTC, daimor requested changes

2021-11-04 20:17 UTC, daimor commented on src/debug/debugSession.ts
> +            if (breakpoint.hitCount && !/^\d+$/.test(breakpoint.hitCount)) {
If `hitCount` allows only integer, why has a `string` type?

2021-11-04 20:17 UTC, daimor commented on src/debug/xdebugConnection.ts
> +      super(rest[0], rest[1], rest[4]);
why not just
`parseInt(rest[4], 10)`
parseInt will return `NaN` for anything else

2021-11-04 20:17 UTC, daimor commented on src/debug/xdebugConnection.ts
> +      this.hitCount = rest[1];
```suggestion
      this.hitCount = rest[1] ? parseInt(rest[1], 10) : null;
```

2021-11-04 20:17 UTC, daimor commented on src/debug/xdebugConnection.ts
> +  public hitCount?: string;
```suggestion
  public hitCount?: number;
```

2021-11-04 20:17 UTC, daimor commented on src/debug/xdebugConnection.ts
> +  public constructor(type: BreakpointType, hitCount?: string);
```suggestion
  public constructor(type: BreakpointType, hitCount?: number);
```

2021-11-04 20:31 UTC, isc-bsaviano commented
@daimor I renamed `hitCount` to `hitCondition` and updated its description to better represent what I'm using it for.

2021-11-05 09:34 UTC, daimor requested changes

2021-11-05 09:34 UTC, daimor commented on src/debug/debugSession.ts
> +            if (breakpoint.hitCondition && !/^\d+$/.test(breakpoint.hitCondition)) {
you can still use `parseInt` here instead of regex

2021-11-05 12:27 UTC, daimor approved these changes

2021-11-05 12:39 UTC, merged