Colorize VSCode ObjectScript Output
intersystems-community/vscode-objectscript pull request #831
Opened 2022-01-17 01:48 UTC by a-boertien

This PR adds functionality to colorize the VSCode ObjectScript output window, including displaying different colors for:
- Successful compilation
- Errored compilation
- Individual errors ('ERROR:', etc. prefixes)
- ObjectScript authorization error
- Classes/routines/file names in compilation status
- Quoted strings, numbers, dates/times

2022-01-17 02:00 UTC, a-boertien commented
Note this is intended as a decent starting point
Possible improvements:
- Handle other permutations of errors
- Handle other warnings/text returned by IRIS that I am not aware of
- Handle languages other than English? (-- does IRIS compilation output change based on language settings?)
- Handle ObjectScript within an error/'TEXT:' output (at the moment, only string/numeric/etc. rules apply: which highlights incorrectly in some circumstances)

2022-01-17 10:41 UTC, daimor commented
Could you add a screenshot with the result?

2022-01-17 14:32 UTC, a-boertien commented
Screenshots added to description

2022-01-17 16:00 UTC, isc-bsaviano commented
I just tested the dev vsix and it adds coloring for every Output channel, not just the ObjectScript one.

2022-01-17 16:27 UTC, gjsjohnmurray commented
@isc-bsaviano is correct. Until https://github.com/microsoft/vscode/issues/19561 gets implemented (or something like it) there's no way to set per-channel grammars.

2022-01-17 17:26 UTC, a-boertien commented
Thanks, I was not aware. That's unfortunate and understandably not acceptable.

I will close this PR and it can be revisited once microsoft/vscode#19561 is resolved, or another workaround is found.

2022-01-18 14:28 UTC, gjsjohnmurray commented
I submitted PR https://github.com/microsoft/vscode/pull/140876 that will allow us to use this when/if accepted.

2022-02-11 22:14 UTC, a-boertien commented
@gjsjohnmurray I had a crack at it.. not sure if it's the best way

2022-02-11 22:37 UTC, gjsjohnmurray requested changes
Looking good, but I think the `mimetypes` array property is now redundant.

2022-02-11 22:37 UTC, gjsjohnmurray commented on package.json
>          "mimetypes": [
I haven't tried this, but I think it should be OK to remove the `mimetypes` array property completely now.

2022-02-12 11:22 UTC, merged