Add links to Learning Services videos in the docs
intersystems-community/vscode-objectscript pull request #832
Opened 2022-01-17 15:54 UTC by isc-bsaviano

2022-01-17 16:31 UTC, gjsjohnmurray requested changes
I left an inline suggestion about changing one of the two "that"s in a sentence to a "which". I don't really mind which, but changing one will improve readability IMO.

2022-01-17 16:31 UTC, gjsjohnmurray commented on docs/RunDebug.md
> +Also, InterSystems Learning Services has produced [a short video](https://learning.intersystems.com/course/view.php?id=1795&ssoPass=1) that walks through the steps in this documentation page that you
```suggestion
Also, InterSystems Learning Services has produced [a short video](https://learning.intersystems.com/course/view.php?id=1795&ssoPass=1) which walks through the steps in this documentation page that you may find useful.

```

2022-01-17 17:57 UTC, gjsjohnmurray approved these changes

2022-01-18 04:05 UTC, isc-rsingh approved these changes

2022-01-18 04:05 UTC, merged